### PR TITLE
Add EC and GO models and tests

### PR DESCRIPTION
**Pull request by bmesuere**
Adds EcNumber and GoTerm models, relations and tests.

The relations are only added at one side because we don't want to accidentally call them in the opposite direction.

Some thoughts:
- maybe add "through" relations to the UniprotEntry model
- we could add FK's to the DB schema to have pretty lines between the table
- we should evaluate if we need all indexes. For example, we don't want to be able to retrieve all UniProt entries associated with a certain ec number, so I don't think we need an index on `ec_number_code`

_[Original pull request](https://github.ugent.be/unipept/unipept/pull/584) by @bmesuere on Thu Jun 16 2016 at 10:53._
_Merged by @bmesuere on Thu Jun 16 2016 at 21:06._

### CODE REVIEW

**Comment by bmesuere** [comment]
Shouldn't the column "ec_number_code" be "code". Also did you take the models from the develop-functional-analysis branch? those should be the most updated ones. Here is a picture of the db how it should look like:
screen shot 2016-06-16 at 11 23 40


_[Original comment](https://github.ugent.be/unipept/unipept/pull/584#issuecomment-32190) by calmalak on Thu Jun 16 2016 at 11:27._

**Comment by bmesuere** [comment]
No, since it's a foreign key of another table (`ec_numbers.code`), we follow the rails convention of calling them _(singular) table name___column name_ thus `ec_number_code`.

Didn't we agree on that in the coffee break when we figured out the cause of the failing tests?


_[Original comment](https://github.ugent.be/unipept/unipept/pull/584#issuecomment-32191) by @bmesuere on Thu Jun 16 2016 at 11:32._

**Comment by bmesuere** [comment]
Ok i guess when you ment that there is no point calling it ec_number_code was only ment for the ec table not the ec cross ref.


_[Original comment](https://github.ugent.be/unipept/unipept/pull/584#issuecomment-32192) by calmalak on Thu Jun 16 2016 at 11:48._

**Comment by ninewise** [comment]
Looks good to me.


_[Original comment](https://github.ugent.be/unipept/unipept/pull/584#issuecomment-32212) by @ninewise on Thu Jun 16 2016 at 17:28._

**Pull request merged**
