### PR TITLE
Update cards on homepage

### PR DESCRIPTION
**Pull request by pverscha**
This PR adds 2 two new cards to the homepage of the Unipept website (one for UMGAP and one for the desktop app) and reorders the other cards.

@ninewise If you have some spare time, could you provide me with a suitable image for the UMGAP that we can use on the homepage?

Current screenshots:
image

### CODE REVIEW

**Comment by pdawyndt** [comment]
I would reverse the order of the tiles on the top row.

**Comment by ninewise** [comment]
Quickly made a logo for the UMGAP; The top left and top middle are the unipept colours (but I don't really like them close together). I prefer the bottem left or top right for light/dark environments. Maybe @bmesuere can give some advice.

I couldn't upload an SVG image here, but I could commit one if you tell me where to put it.

logo

**Comment by pverscha** [comment]
@ninewise Oooh, I like them! Especially the top right one is one of my favourites! If (after approval from @bmesuere) you would like to add the images, you can add them to the "assets/images" folder (name it something like "home_feature_umgap.svg"). Thanks!

**Comment by bmesuere** [comment]
I prefer the ones using white as one of the two colors.

**Review by bmesuere — APPROVED** [review]

**Pull request merged**
