### PR TITLE
Add functional analysis

### PR DESCRIPTION
**Pull request by beardhatcode**
Releasing: see #647
Currently loading data: https://unipept.ugent.be/load-status.txt

---

- [x] Clean Ruby code to get FA data
- [x] Read data into `GOTerm` and `ECNumber` classes
- [x] Add batches to `GOTerm` and `ECNumber`
- [x] Make visualisations
  - [x] Table of GO terms 
  - [x] ... with QuickGO 
  - [x] Table of EC Numbers 
  - [x] Table of GO terms 
  - [x] Correct text and tooltips
- [ ] Figure out how to set cutoff
- [x] Correct content of tooltips
- [x] Save EC tree btn
- [x] Check what code can be shared with single pept
- [x] Calculate a measure of evidence 
  - *X% of ... had annotations*
- [x] make PR for [`feature/loading-images`](https://github.ugent.be/unipept/unipept/tree/feature/loading-images)
- [x] Run backen code on HPC
  - [x] Make PR to use `long` for peptide id
  - [ ] See if we can improve sped up the backend code 
- [x] Allow sorting on different metric in FA view
- [x] Compress data in the database (https://blog.beardhatcode.be/2018/04/mysqlimport.html)
- [x] Remove unused metrics
- [x] Check wat pollyfills are needed in the loader
- [x] Consistency: "GO Term(s)" and "EC number(s)"

Bugs:
- [x] bug in peptidome buttons

_[Original pull request](https://github.ugent.be/unipept/unipept/pull/623) by @beardhatcode on Fri Nov 10 2017 at 14:30._
_Merged by @beardhatcode on Tue Aug 28 2018 at 16:42._

### CODE REVIEW

**Comment by beardhatcode** [comment]
Rebasing this on on #625

_[Original comment](https://github.ugent.be/unipept/unipept/pull/623#issuecomment-73275) by @beardhatcode on Thu Feb 15 2018 at 14:10._

**Comment by beardhatcode** [comment]
The old version of this branch is availible as [feature/functionalAnalysisPept2FA-old](https://github.ugent.be/unipept/unipept/tree/feature/functionalAnalysisPept2FA-old)

- [x] todo remove feature/functionalAnalysisPept2FA-old branch

_[Original comment](https://github.ugent.be/unipept/unipept/pull/623#issuecomment-73604) by @beardhatcode on Mon Feb 26 2018 at 17:06._

**Comment by beardhatcode** [comment]
FA info for Gut 7

screen shot 2018-02-28 at 15 13 59

screen shot 2018-02-28 at 15 14 13


_[Original comment](https://github.ugent.be/unipept/unipept/pull/623#issuecomment-73717) by @beardhatcode on Wed Feb 28 2018 at 15:15._

**Comment by beardhatcode** [comment]
The idea to optimise gathering the data for FA is to create an extra FA field in sequences to store the (compressed) functional analyis data per sequence. If this is too large we will look for a cut off. 

```sql
SELECT
	s.id, s.`sequence` ,GROUP_CONCAT(g.go_term_code SEPARATOR ',')
FROM
	sequences s
RIGHT JOIN peptides p ON s.id = p.original_sequence_id
RIGHT JOIN go_cross_references g ON p.uniprot_entry_id = g.uniprot_entry_id
GROUP BY `sequence`
```
(This is obviously too slow)

_[Original comment](https://github.ugent.be/unipept/unipept/pull/623#issuecomment-73827) by @beardhatcode on Fri Mar 02 2018 at 17:04._

**Comment by beardhatcode** [comment]
@ninewise , I quickly wrote some backend code for caching the counts of GO and EC numbers at the sequences in https://github.ugent.be/unipept/unipept/pull/623/commits/4b18a6b999a621355687e5e5ec7dd14c4132af42 . Could you give it a quick look?

Now, it adds 2 JSONs to each row of sequences (one with and without il) that contain content of the following form (without spacing):

```json
{
  "num": {
    "all": 1,
    "EC": 1,
    "GO": 1
  },
  "data": {
    "GO:0016569": 1,
    "GO:0006281": 1,
    "GO:0000781": 1,
    "EC:2.7.11.1": 1,
    "GO:0004674": 1,
    "GO:0005634": 1,
    "GO:0005524": 1,
    "GO:0016301": 1
  }
}
```

For swisprot, calculating `FAs.tsv.gz` takes about 39s (on my laptop with 4G ram allocated to java)

The goal is to store these values gzipped instead, but I don't know how i can get gzipped data in a tsv for importing. Any pointers? Or notes on the things in https://github.ugent.be/unipept/unipept/pull/623/commits/4b18a6b999a621355687e5e5ec7dd14c4132af42 ?

_[Original comment](https://github.ugent.be/unipept/unipept/pull/623#issuecomment-73975) by @beardhatcode on Tue Mar 06 2018 at 11:53._

**Comment by beardhatcode** [comment]
Todo look at https://github.ugent.be/unipept/unipept/pull/619

_[Original comment](https://github.ugent.be/unipept/unipept/pull/623#issuecomment-74048) by @beardhatcode on Wed Mar 07 2018 at 18:26._

**Comment by beardhatcode** [comment]
@bmesuere , the current version has all the features MPA had but with precalculated fa results. 
I would like to measure how long the backend aggregation takes and how the results look on the total dataset.

_[Original comment](https://github.ugent.be/unipept/unipept/pull/623#issuecomment-74145) by @beardhatcode on Fri Mar 09 2018 at 15:01._

**Comment by beardhatcode** [comment]
How should the following sentence be reformulated?

> The shown percentage indicates the fraction of the sequences that contain that GO term multiplied by the probability that a sequence indicates that GO-term. The shown results are limited to peptites that are under **Eukaryota**. 

- [x] reformulate

_[Original comment](https://github.ugent.be/unipept/unipept/pull/623#issuecomment-74845) by @beardhatcode on Mon Mar 26 2018 at 10:25._

**Comment by beardhatcode** [comment]
- [x] https://github.ugent.be/unipept/unipept/pull/623/commits/cd32fa425b2be67ea1952e45d0af55e8eb884e40 relies on PR https://github.ugent.be/unipept/unipept-visualizations/pull/22 to be accepted and merged

_[Original comment](https://github.ugent.be/unipept/unipept/pull/623#issuecomment-74872) by @beardhatcode on Mon Mar 26 2018 at 19:37._

**Comment by beardhatcode** [comment]
This branch has been rebased on the changes proposed in #625 .

_[Original comment](https://github.ugent.be/unipept/unipept/pull/623#issuecomment-77564) by @beardhatcode on Mon May 28 2018 at 14:21._

**Comment by beardhatcode** [comment]
I calculated the trust for each GO/EC by taking the average of `protWithAnnotaion/prot` where `prot` is the amount of proteins that match a peptide, and `protWithAnnotaion` the number of proteins that have an GO/EC annotion. 

Oddly enough this gives very high trusts scores.

setting `window.showTrust = true` on morty will show trust values

_[Original comment](https://github.ugent.be/unipept/unipept/pull/623#issuecomment-77614) by @beardhatcode on Wed May 30 2018 at 18:26._

**Comment by bmesuere** [comment]
Single peptide page:
- [x] The badge with number of proteins next to "protein matches" made sense when this wasn't the first tab, now it is kind of useless.
- [x] The question mark that opens an info modal is a bit confusing, since it's a link within a link. Maybe the help button (or text) can be moved inside the tab.
- [x] The buttons in the tab navigation could be moved inside the tab itself. Together with the previous suggestions, this would probably make some space in the header to rename GO to GO terms and EC to EC numbers?
- [x] Maybe the summary at the top could include something about the function as well?
- [x] The png export of the trees uses a serif font. This can be fixed by setting a font style on the svg tag (maybe needs to be done in unipept-visualisation lib) (⇒ see https://github.ugent.be/unipept/unipept-visualizations/issues/25 )
  - [x] Update lib to 1.7.1 and test if fixed
- [x] GO tooltip: right now the GO number is on the same line of the (sometimes long) name, maybe it looks better if we move it the the line below: "$name $number \n $domain" -> "$name \n $domain - $number"?
- [x] When there are no ec annotations, the "download tree" button is still shown (maybe this is also the case without go annotations)
- [x] In the EC and GO table headers, rename "count" to "proteins"?

_[Original comment](https://github.ugent.be/unipept/unipept/pull/623#issuecomment-77880) by @bmesuere on Mon Jun 11 2018 at 16:31._

**Comment by bmesuere** [comment]
Multi peptide:
- [x] "We managed to match 1994 of your 2005 peptides." -> "We managed to match 1994 of your 2005 peptides. Unfortunately, xx peptides couldn't be found." Link xx peptides to a popover containing the contents of the missed peptides tab and eliminate the tab itself. 
- [x] The height of the text area can then be increased to match the height of the left part of the card.
- [x] Move the Hierarchical outline to a 4th tab of the upper tab bar.
- [x] Show found in % of peptides to the default amount table view.
- [x] The length of the bars in the amount table should correspond to the currently shown metric
- [x] icon + select gives issue on chrome on mac:
image
- [x] The text at the top of the GO box is a bit generic. This could be replaced with the number of peptides that have at least one GO annotation. I would remove the second sentence explaining the "filtered" view, but would introduce a more prominent warning if we're filtering on a taxon (colored background, and potentially the option to undo the filtering).
- [x] Maybe that same area can be split in 2 with the left containing the text and the right containing the settings/controls that are in the header right now (and at the bottom)
- [x] The save tree as image button fo the ec numbers should be closer to the tree
- [x] The text on the Save CSV button could be a bit more verbose (save table as CSV?)
- [x] The UI of the expanded row is a bit strange. I think it would be better if the bottom border of the actual row that is expanded is 0 and that the expansion part uses the same drop shadow as cards (no inset shadow)
  - Took an other approach
- [x] The tree in the expanded row uses color to highlight where that function was found. This is not immediately clear for new users. Maybe the blue used here is too similar to the blue used in the actual taxonomy graph.
  - unipept orange is now used
- [x] Maybe increase the number of rows that gets added after each click (e.g. "show 10 more" for the first 2 clicks, then switch to 50 or 100 and then to all?).
  - After 2 clicks a tip is shown to "<kbd>shift+click</kbd>  for 100"
- [x] Text could be tweaked to "Show 10 more rows - showing xx of xxx"

Future:
- [ ] A search box would help here too, maybe something for a next version
- [ ] The use as base feature needs more explanation (potentially hide the feature for the initial release?)
- [ ] For a future update: The hierarchy is linked with the sunburst/treemap/treeview, but after moving them to the same tab element, this isn't clear anymore. A solution for this is to add a search box to the tab bar that contains the name of the currently selected element + allows the user to search for taxa. This woud also link the sunburst, treemap and treeview with each other.

_[Original comment](https://github.ugent.be/unipept/unipept/pull/623#issuecomment-77902) by @bmesuere on Tue Jun 12 2018 at 15:26._

**Comment by bmesuere** [comment]
SPA
- [x] Functionality -> Function 
- [x] The lowest common ancestor was -> The lowest common ancestor is
- [x] https taxon links in summary
- [x] UniProt entries: help text should include something like "exact match"
- [x] GO tooltip: maybe "matched proteins with a GO annotation" is better than "matched annotated proteins"?
- [x] lineage tree help text contains "undefined"
- [x] Position the download EC tree button better 
- [ ] peptides without ec annotations have an incorrect text on the ec tab: https://morty.ugent.be/sequences/MDGTEYIIVK/equateIL
- [x] ~I don't know if this will work, but maybe mark the help texts on the tabs with a vertical blue line at the left, similar to the pullouts at https://unipept.ugent.be/clidocs#installation~

_[Original comment](https://github.ugent.be/unipept/unipept/pull/623#issuecomment-78169) by @bmesuere on Tue Jul 03 2018 at 20:59._

**Comment by bmesuere** [comment]
MPA
- [x] newline before "Unfortunately"
- [x] when reducing the screen with, below some breakpoint, the text area jumps below the form buttons on the result page
- [x] In full screen mode, the background of the treeview and treemap is black
- [x] The horizontal "active tab marker" is missing from the go/ec panel when previously opened full screen view on that page
- [x] Filtered message: "... limited to the xxx peptides specific to taxon name (rank)."
- [ ] showing more rows: not convinced of the layout: showing xx of xx is ok, but the down chevron is in front of it, while the action "show more" is behind it. The up chevron to hide the rows is visually on the same "button"/row but has a different action and no textual explanation. The shift+click message can be confusing and is incomplete "shift+click for 100"
- [x] Is there a reason why a different down chevron is used for the show more rows and the expand function?
- [x] When expanding a row, is there a reason why the slice of organism is gray instead of yellow?
  - No, unintentional side effect, now fixed 
- [x] Tooltips for the download button of a row?
- [ ] Tooltips for the favorite button of a row?
  - Postponed till it is public
- [ ] Maybe add some margin around the save as image button for expanded rows
  - The area is small, I would rather keep it in the corner
- [x] We use 2 separate icons for download. Is there a reason for this?
  - No, fixed
- [ ] favorite help text: some more info: saved between visits, why would you filter? ... also annotaion -> annotation
  - Postponed till it is public
- [ ] help modal has no explicit close button
- [ ] there is a 6px space below the footer

I still think the favorite and compare feature need some work before these are ready for production. For example, by default, I would always compare to the entire dataset and make this comparison a bit more explicit. The rest looks very very good. I would 
- [x] hide these features and merge this branch
- [x] test the new UniProt version on morty
- create a new release and deploy on unipept.ugent.be with the june UniProt data (Unipept 4.0?)
- send this out to a few people to test
- focus on the manuscript
- once the manuscript is submitted and we're waiting for the manuscript to be reviewed, make a second iteration based on the feedback we got from users and our todo list.

_[Original comment](https://github.ugent.be/unipept/unipept/pull/623#issuecomment-78181) by @bmesuere on Wed Jul 04 2018 at 14:14._

**Comment by beardhatcode** [comment]
Would it be a good idea to use the evidence score to optimise the tresshold for fa filtering

_[Original comment](https://github.ugent.be/unipept/unipept/pull/623#issuecomment-78266) by @beardhatcode on Tue Jul 10 2018 at 22:07._

**Pull request closed without merging**
