### PR TITLE
Feature/configure script

### PR DESCRIPTION
**Pull request by ninewise**
Adding a configuration script to configure the backend should fix the current problems with the config/makefile combo and the mac incompatibility.

Features:
- [x] Switching between local (testing) and server (production) configuration
  - local: swissprot only, less memory
  - production: swissprot + uniprot, more memory
- [x] Selecting binaries to use 
  - gzcat/zcat
  - gzip/pigz
  - unzip (-DD is not supported on mac)
- [x] Picking source files (swissprot/trembl) and their possible download location
- [x] Check if all dependencies are present?
- [x] Also configure commands in `proteomes.sh` and `type_strains.sh`
- [x] Configure `awk`, `gmktemp` and `join`.

_[Original pull request](https://github.ugent.be/unipept/unipept/pull/566) by @ninewise on Mon Mar 14 2016 at 14:11._
_Merged by @ninewise on Thu May 19 2016 at 14:31._

### CODE REVIEW

**Comment by bmesuere** [comment]
Nice work! Seems to work fine on my mac. Some comments:
- add space between [default value] and prompt
- set 5 as default min peptide length
- add `(inclusive)` or something alike to min and max length description
- the default data path is something different than what we used before?
- `Where should I download and extract the taxon zip?` and `Where should I download the source xml files?` might let a user think he must give the download source. Maybe use `store` instead of `download` (and maybe add `downloaded` as adjective to taxon zip/source xml)
- use the same value for `-Xmx` and `-Xms` and rephrase as something like "how much memory should java use?"
- split the sort command in separate questions (sort command, memory, threads)? locale should always be used
- add suggestions for the mac variants in the questions. For example "Which sort command (e.g. sort, gsort,...) should I use?
- with `how should i compress` it's not entirely clear what's the intention (with the `-`)


_[Original comment](https://github.ugent.be/unipept/unipept/pull/566#issuecomment-27192) by @bmesuere on Mon Mar 14 2016 at 14:24._

**Comment by ninewise** [comment]
Fixed most of the remarks. Some discussion:
1.  the default data path is something different than what we used before?
   
   It seemed weird to use `../../data` as a base directory. This would seem very random for new users. Then again, it's easy because it's what we use and it makes kind of sense as it's just outside the repository.
2.  split the sort command in separate questions (sort command, memory, threads)? locale should always be used
   
   I think it's better to keep this as one command. After all, if we offer to chance the memory, we might as well offer to change `--temporary-directory`, `--compress-program` and others. And, suppose someone changed the `sort` command to something with different names for options, our options wouldn't work.


_[Original comment](https://github.ugent.be/unipept/unipept/pull/566#issuecomment-27200) by @ninewise on Mon Mar 14 2016 at 15:46._

**Comment by bmesuere** [comment]
Is the suggested option always our/the default value, or is the previously chosen value shown?


_[Original comment](https://github.ugent.be/unipept/unipept/pull/566#issuecomment-27514) by @bmesuere on Sat Mar 19 2016 at 11:30._

**Comment by ninewise** [comment]
The previous values are stored in `.default-config` and used as defaults the next time configure is run.


_[Original comment](https://github.ugent.be/unipept/unipept/pull/566#issuecomment-27649) by @ninewise on Mon Mar 21 2016 at 14:11._

**Comment by ninewise** [comment]
I think this is ready. We should probably test it on the server when the april version has been build with the previous backend, but if the configure script exits normally, everything ought to work.


_[Original comment](https://github.ugent.be/unipept/unipept/pull/566#issuecomment-29530) by @ninewise on Fri Apr 15 2016 at 11:55._

**Pull request closed without merging**
