### PR TITLE
Peptidome 2.0

### LINKED ISSUE #157: enable adding genomes from full screen mode
_[Original issue](https://github.ugent.be/unipept/unipept/issues/157) by @bmesuere on Sat Sep 21 2013 at 14:55._
_Closed by @bmesuere on Thu Jul 02 2015 at 15:20._

### LINKED ISSUE #307: add more info to cluster tooltip
> add size of intersection and union to popup menu to explain the similarity value

_[Original issue](https://github.ugent.be/unipept/unipept/issues/307) by @bmesuere on Sun May 11 2014 at 14:30._
_Closed by @bmesuere on Thu Jul 02 2015 at 15:20._

### LINKED ISSUE #353: allow selection of RefSeq draft genomes
Apart from tabs that allow to select from complete and custom genomes, another tab could be added where users can select from RefSeq draft genomes. Some draft genomes are near complete, so that it makes sense to also add them to the analysis.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/353) by @pdawyndt on Tue May 27 2014 at 21:48._
_Closed by @bmesuere on Thu Jul 02 2015 at 15:20._

### LINKED ISSUE #416: save peptidome analysis state between sessions
- store data in local storage
- check out if we have to save after every change, or only on page leave
- on loading, check if a previous session is stored and offer to restore
- in the future, we can maybe offer to save (and name) sessions

_[Original issue](https://github.ugent.be/unipept/unipept/issues/416) by @bmesuere on Wed Sep 17 2014 at 14:04._
_Closed by @bmesuere on Thu Jul 02 2015 at 15:20._

### LINKED ISSUE #419: provide some sort of group add for own genomes
When you have a lot of "my genomes", adding a bunch of them takes a lot of time. Saving the session (#416) will also help with this problem.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/419) by @bmesuere on Thu Sep 18 2014 at 09:35._
_Closed by @bmesuere on Thu Jul 02 2015 at 15:20._

### LINKED ISSUE #426: loading similarities during initial matrix animation is choppy
_[Original issue](https://github.ugent.be/unipept/unipept/issues/426) by @bmesuere on Wed Oct 08 2014 at 10:36._
_Closed by @bmesuere on Thu Jul 02 2015 at 15:20._

### LINKED ISSUE #460: switch from bioprojects to assemblies for peptidome analysis
Because the information in the `prokaryotes.txt` file isn't available anymore, and because of http://nar.oxfordjournals.org/content/43/D1/D599.full.pdf+html we have to switch strategies to select peptidomes. Using assemblies seems to be an alternative.
- data sources: <add me> @ninewise 
- assembly level definitions: https://www.ebi.ac.uk/ena/browse/genome-assembly-database

_[Original issue](https://github.ugent.be/unipept/unipept/issues/460) by @pdawyndt on Mon Feb 16 2015 at 15:54._
_Closed by @bmesuere on Thu Jul 02 2015 at 15:20._

### LINKED ISSUE #484: clustering popup does not disappear when list of selected genomes is emptied
If you click a node in the graph of the Unique Peptide Finder, and then empty the list of selected genomes while the fixed popup is still visible, the popup stays visible and cannot be removed. I guess that emptying the list of genomes should remove any visible popup the same way as is done when removing a single entry from the list.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/484) by @pdawyndt on Tue Apr 07 2015 at 15:21._
_Closed by @bmesuere on Thu Jul 02 2015 at 15:20._

### LINKED ISSUE #491: filter genomes based on "type strain/type specimen"
@bmesuere Please read through the following paper:

Federhen, S. (2014). [Type material in the NCBI Taxonomy Database](http://nar.oxfordjournals.org/content/early/2014/11/14/nar.gku1127.full). Nucleic acids research, gku1127.

_application of shared k-mers (and ANI-like measure that references the Meier-Kolthoff et al. 2013 paper) to type strain (mainly bacteria, but also others); example of Dickeya and Klebsiella oxytoca/Raoultella ornithinolytica; could serve as a reference for the type strain filtering; need to check how the type strain filtering can be implemented in Unipept; currenly does not seem to be directly annotated on the assemblies, but may be derived using a detour_

Scott Federhen has sent me this article, together with an invitation to participate in a mini-symposium at the NCBI about the topic of "sequence from type". The article has some use cases that we could include in the peptidome-clustering paper (I have added it to the literature list of this paper), but it would also be quite interesting to have the "type strain" information available for the proteomes. I haven't been able to check how easy this data is accessible for the assembly records (GenBank seems to be down today), but the article seems to indicate that this information is either available directly with the assembly records, or can be found using some of its links. It would definitely be interesting to have this information an use it for filtering the genomes especially when the number of available genomes keeps growing. We could also flag the genomes that are from type material in the clustering en unique peptide finder.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/491) by @pdawyndt on Fri Apr 17 2015 at 12:32._
_Closed by @bmesuere on Thu Jul 02 2015 at 15:20._

### LINKED ISSUE #492: investigate replacing jquery UI by dragula
http://bevacqua.github.io/dragula/

_[Original issue](https://github.ugent.be/unipept/unipept/issues/492) by @bmesuere on Tue Apr 21 2015 at 09:41._
_Closed by @bmesuere on Thu Jul 02 2015 at 15:20._

### LINKED ISSUE #502: exception in get_lca
```
A NoMethodError occurred in peptidome#get_lca:

  undefined method `size' for nil:NilClass
  app/controllers/peptidome_controller.rb:73:in `get_lca'


-------------------------------
Request:
-------------------------------

  * URL        : http://unipept.ugent.be/peptidome/get_lca
  * HTTP Method: GET
  * IP address : 207.46.13.31
  * Parameters : {"controller"=>"peptidome", "action"=>"get_lca"}
  * Timestamp  : 2015-06-11 07:30:55 UTC
  * Server : sherlock
  * Rails root : /home/bmesuere/rails/releases/20150326160904
  * Process: 18696
```

_[Original issue](https://github.ugent.be/unipept/unipept/issues/502) by @bmesuere on Thu Jun 11 2015 at 09:41._
_Closed by @bmesuere on Thu Jul 02 2015 at 15:20._

### PR DESCRIPTION
**Pull request by bmesuere**
Rewrite of the peptidome part of the website. This includes:
- Use assemblies instead of bioprojects
- Present the proteomes in a filterable table instead of a tree
- Remove the drag to add behaviour
- Add progress notifications
- Add more info to the similarity matrix tooltip
- Add more similarity metrics
- Save the analysis state and automatically reload on the next visit
- Improve initial loading animation of similarity matrix
- Add advanced full screen mode
- Similarity calculation is now 8-10 times faster
- Fix bugs

# 
- [x] Retire the use of bioproject ids and transition to assembly ids (#460)
  - [x] Add data
    - [x] Add new tables to the database scheme
    - [x] Create ruby models + annotate
    - [x] Update tests
    - [x] Update preprocessing scripts
    - [x] Clean old tables
    - [x] type strain info (@ninewise) (#491)
    - [x] Add sql, with and without indexes
  - [x] Find a new way to select genomes as the tree will probably break with 30.000 genomes
    - [x] Enable the add buttons
    - [x] Enable the checkboxes and add all button
    - [x] Clicking row = toggle checkbox
    - [x] Make the lineage links clickable
    - [x] Add rank information to the suggestion list
    - [x] Enable drag and drop
    - [x] Remove old selection tree code
    - [x] Enable adding draft genomes (#353)
    - [x] Figure out on which fields we want to filter and include them in the metadata
      - [x] Assembly level
      - [x] Genome representation
      - [x] type strain
    - [x] Search for is:complete by default
    - [x] Add filters to the search suggestions
    - [x] Add a search popover with advanced options
    - [x] Smart token replacement
    - [x] Fix editing taxon tokens
    - [x] Add paging
    - [x] Add filter for already added
    - [x] Improve layout of settings popover
    - [x] Code cleanup and documentation
  - [x] Rename genomes/proteomes/peptidomes, discuss with @pdawyndt 
  - [x] Add more metadata
  - [x] Fix a few bioproject links
- add notifications
  - [x] loading genomes
  - [x] sorting
  - [x] calculating pancore
  - [x] calculating similarities
  - [x] download sequences
  - [x] reprocess my genomes 
  - [x] process mygenomes
- [x] The remove button of the popover is broken
- [x] Add more left margin to the graph to support numbers over 1M
- [x] Swapping tree nodes results in errors
- [x] add + button to my genomes table (#419)
- [x] remove all drag and drop code
- [x] implement dragula and remove jqueryUI (#492)
- [x] Investigate mygenomes import unresponsiveness
- [x] Save peptidome analysis state between sessions (#416)
- Improved full screen mode
  - [x] Use the bar-based model used in the MPA
  - [x] Enable switching between visualisations
  - [x] Enable adding genomes (#157)
- [x] alternative similarity metrics
  - default: intersection / union
  - intersection / min(#a, #b)
  - intersection / avg(#a, #b)
  - intersection / max(#a, #b)
  - intersection / (sqrt (2_#a_#b)/sqrt (#a^2+#b^2))
  - [x] rename metrics
- [x] Show more info in the cluster tooltip (#307)
- [x] Improve cluster animation by using some sort of data queue (#426)
- Add the option to hide the tree or the matrix (#306) -> won't implement
- [x] Offer a share link -> moved to next version: #512
- [x] fix exception in get_lca (#502)

closes #157, closes #307, closes #353, closes #416, closes #419, closes #426, closes #460, closes #484, closes #491, closes #492, closes #502   

_[Original pull request](https://github.ugent.be/unipept/unipept/pull/472) by @bmesuere on Thu Mar 19 2015 at 15:24._
_Merged by @bmesuere on Thu Jul 02 2015 at 15:20._

### CODE REVIEW

**Comment by bmesuere** [comment]
Adding the selection tree with 17k nodes to the page takes 10+ seconds :(


_[Original comment](https://github.ugent.be/unipept/unipept/pull/472#issuecomment-16087) by @bmesuere on Thu Apr 16 2015 at 14:54._

**Comment by bmesuere** [comment]
The new table + filter is now fully implemented, the my proteomes table was refactored and JQuery UI was dropped. Things that need to be tested:
- [x] Add "my proteomes" while being updated
- [x] Drag and drop reorder while calculating
- [x] Cursor while dragging


_[Original comment](https://github.ugent.be/unipept/unipept/pull/472#issuecomment-16810) by @bmesuere on Wed Apr 29 2015 at 14:32._

**Comment by pdawyndt** [comment]
@bmesuere er staat nu "Click the plus-button to add your own proteomes." met een pijl naar boven die naar het vuilbakje lijkt te verwijzen. Misschien moet dit nog eens herbekeken worden.


_[Original comment](https://github.ugent.be/unipept/unipept/pull/472#issuecomment-16843) by @pdawyndt on Thu Apr 30 2015 at 11:40._

**Comment by bmesuere** [comment]
The analysis is now saved on page leave and restored when the user clicks the restore button.
- [x] Add support for my proteomes
- [x] Don't take the assembly version into account


_[Original comment](https://github.ugent.be/unipept/unipept/pull/472#issuecomment-16915) by @bmesuere on Fri May 01 2015 at 17:07._

**Comment by bmesuere** [comment]
Some shower inspiration:
- [x] To prevent the user from getting stuck in an invalid state AND automatically resume a previous analysis

```
if (previous analysis is present) {
    if (previous analysis wasn't auto loaded before) {
        auto load previous analysis
    } else {
        load demo
        ask to load previous analysis
    }
} else {
    load demo
}
```
- [x] Report if a proteome couldn't be loaded (e.g. because it was removed from uniprot)
- [x] Offer a share link
  - if it contains local proteomes, report that it won't work on other computers
  - if a state was loaded from a link, and a local proteome wasn't present in the browser, report it to the user


_[Original comment](https://github.ugent.be/unipept/unipept/pull/472#issuecomment-16948) by @bmesuere on Sat May 02 2015 at 10:51._

**Comment by bmesuere** [comment]
The last 2 commits made the similarity calculation 4 times faster, and 8-10 times faster compared to master.
I noticed some JS error when
- swapping branches -> couldn't reproduce
- clicking the restore status link -> fixed in 47588eb


_[Original comment](https://github.ugent.be/unipept/unipept/pull/472#issuecomment-17078) by @bmesuere on Tue May 05 2015 at 10:53._

**Comment by bmesuere** [comment]
unique peptide finder unipept


_[Original comment](https://github.ugent.be/unipept/unipept/pull/472#issuecomment-18838) by @bmesuere on Thu Jul 02 2015 at 13:39._

**Comment by bmesuere** [comment]
@pdawyndt Shouldn't we remove our 'weighted average' since we have no correct name for it and no real reference where it's used? We could replace it by the [Ochiai coefficient](https://en.wikipedia.org/wiki/Cosine_similarity#Ochiai_coefficient): divide by sqrt(#A*#B)
See #513


_[Original comment](https://github.ugent.be/unipept/unipept/pull/472#issuecomment-18840) by @bmesuere on Thu Jul 02 2015 at 14:18._

**Pull request merged**
